# -*- coding: utf-8 -*-
"""
Problem 1

If we list all the natural numbers below 10 that are multiples of 3 or 5, 
get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
"""
nnum=1000

num_list = []
for i in range(3, nnum):
    if i%3 == 0:
        num_list.append(i)
    if i%5 == 0:
        if i not in num_list:
            num_list.append(i)
            
print(sum(num_list))

#%%
"""
Problem 2 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
"""

i = 1
flist = [0, 1]
fib_list = []
fnum = 1
while fnum <= 4000000:
    fnum = fnum + flist[-2]
    flist.append(fnum)
if fnum > 4000000:
    flist.pop(-1)
for i in flist:
    if i%2 == 0:
        fib_list.append(i)
print(sum(fib_list))

#%%
"""
Problem 3

The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
"""

primefactor = 600851475143
pfsquare = int(primefactor**0.5)
pf_list = []
i = 2
while i*i < primefactor:
    while primefactor%i == 0:
        
        primefactor = primefactor/i
        
    i = i+1

print(primefactor)



#%%
"""
Problem 4

A palindromic number reads the same both ways. The largest palindrome made 
from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.
"""
n = 999
result = []

for i in range(n, n-100, -1):
    for k in range(n, n-100, -1):
        num = []
        num1= []
        num2= []
        num.append(i*k)
        num = str(num)
        num1.append(num[1])
        num1.append(num[2])
        num1.append(num[3])
        num2.append(num[6])
        num2.append(num[5])
        num2.append(num[4])
        if num2 == num1:
           result.append([num])
            
    

print(result[0])
    
        


#%%
"""
Problem 5

2520 is the smallest number that can be divided by each of 
the numbers from 1 to 10 without any remainder.
What is the smallest positive number that is evenly 
divisible by all of the numbers from 1 to 20?
"""

num1 = 2520
fn = 2520
while True:
    count = 0
    for i in range(10, 20):
        if fn % i != 0:
            count += 1
    if count > 0:
        fn += num1
    else:
        break
    
print(fn)
            
